//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_with_database.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SoapSoap")]
    public interface SoapSoap {
        
        // CODEGEN: Generating message contract since element name GetDriverNameOfTripResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNameOfTrip", ReplyAction="*")]
        Car_with_database.ServiceReference1.GetDriverNameOfTripResponse GetDriverNameOfTrip(Car_with_database.ServiceReference1.GetDriverNameOfTripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNameOfTrip", ReplyAction="*")]
        System.Threading.Tasks.Task<Car_with_database.ServiceReference1.GetDriverNameOfTripResponse> GetDriverNameOfTripAsync(Car_with_database.ServiceReference1.GetDriverNameOfTripRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNameOfTripRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNameOfTrip", Namespace="http://tempuri.org/", Order=0)]
        public Car_with_database.ServiceReference1.GetDriverNameOfTripRequestBody Body;
        
        public GetDriverNameOfTripRequest() {
        }
        
        public GetDriverNameOfTripRequest(Car_with_database.ServiceReference1.GetDriverNameOfTripRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNameOfTripRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TripId;
        
        public GetDriverNameOfTripRequestBody() {
        }
        
        public GetDriverNameOfTripRequestBody(int TripId) {
            this.TripId = TripId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNameOfTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNameOfTripResponse", Namespace="http://tempuri.org/", Order=0)]
        public Car_with_database.ServiceReference1.GetDriverNameOfTripResponseBody Body;
        
        public GetDriverNameOfTripResponse() {
        }
        
        public GetDriverNameOfTripResponse(Car_with_database.ServiceReference1.GetDriverNameOfTripResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNameOfTripResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDriverNameOfTripResult;
        
        public GetDriverNameOfTripResponseBody() {
        }
        
        public GetDriverNameOfTripResponseBody(string GetDriverNameOfTripResult) {
            this.GetDriverNameOfTripResult = GetDriverNameOfTripResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapSoapChannel : Car_with_database.ServiceReference1.SoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapSoapClient : System.ServiceModel.ClientBase<Car_with_database.ServiceReference1.SoapSoap>, Car_with_database.ServiceReference1.SoapSoap {
        
        public SoapSoapClient() {
        }
        
        public SoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Car_with_database.ServiceReference1.GetDriverNameOfTripResponse Car_with_database.ServiceReference1.SoapSoap.GetDriverNameOfTrip(Car_with_database.ServiceReference1.GetDriverNameOfTripRequest request) {
            return base.Channel.GetDriverNameOfTrip(request);
        }
        
        public string GetDriverNameOfTrip(int TripId) {
            Car_with_database.ServiceReference1.GetDriverNameOfTripRequest inValue = new Car_with_database.ServiceReference1.GetDriverNameOfTripRequest();
            inValue.Body = new Car_with_database.ServiceReference1.GetDriverNameOfTripRequestBody();
            inValue.Body.TripId = TripId;
            Car_with_database.ServiceReference1.GetDriverNameOfTripResponse retVal = ((Car_with_database.ServiceReference1.SoapSoap)(this)).GetDriverNameOfTrip(inValue);
            return retVal.Body.GetDriverNameOfTripResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Car_with_database.ServiceReference1.GetDriverNameOfTripResponse> Car_with_database.ServiceReference1.SoapSoap.GetDriverNameOfTripAsync(Car_with_database.ServiceReference1.GetDriverNameOfTripRequest request) {
            return base.Channel.GetDriverNameOfTripAsync(request);
        }
        
        public System.Threading.Tasks.Task<Car_with_database.ServiceReference1.GetDriverNameOfTripResponse> GetDriverNameOfTripAsync(int TripId) {
            Car_with_database.ServiceReference1.GetDriverNameOfTripRequest inValue = new Car_with_database.ServiceReference1.GetDriverNameOfTripRequest();
            inValue.Body = new Car_with_database.ServiceReference1.GetDriverNameOfTripRequestBody();
            inValue.Body.TripId = TripId;
            return ((Car_with_database.ServiceReference1.SoapSoap)(this)).GetDriverNameOfTripAsync(inValue);
        }
    }
}
