//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_with_database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripID { get; set; }
        public string startingAddress { get; set; }
        public string startingZip { get; set; }
        public string startingCity { get; set; }
        public string destinationAddress { get; set; }
        public string destinationZip { get; set; }
        public string destinationCity { get; set; }
        public System.DateTime time { get; set; }
        public int driverID { get; set; }
        public int numberOfSeats { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
